services:
  backend:
    build: .
    depends_on:
      - postgres
      - rabbitmq
      - mosquitto
    ports:
      - "8080:8080"

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - mosquitto
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  mosquitto:
    image: eclipse-mosquitto:2.0.17
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto-conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "test", "-C", "1", "-W", "3"]
      interval: 5s
      timeout: 5s
      retries: 5
      
